added testing to build script

diff --git a/build-run-docker b/build-run-docker
--- a/build-run-docker
+++ b/build-run-docker
@@ -11,7 +11,10 @@ DOCKER_IMAGE_FULL=$(grep 'image:' $DOCKER_COMPOSE_FILE | awk '{ print $2 }')
 DOCKER_IMAGE_NAME=$(echo $DOCKER_IMAGE_FULL | cut -d':' -f1)  # Extracts only the name, without the tag
 DOCKER_IMAGE_TAG=$(echo $DOCKER_IMAGE_FULL | cut -d':' -f2)  # Extracts only the tag, without the name
 echo "Docker Image Full is $DOCKER_IMAGE_FULL . Name is $DOCKER_IMAGE_NAME ."
-
+if ! dotnet test NetworkMonitorProcessor-debian12.csproj ; then
+    echo "Test failed. Exiting..."
+    exit 1
+fi
 # Step 2: Build and publish the Docker container
 if ! dotnet publish NetworkMonitorProcessor-debian12.csproj --os linux --arch x64 -c Release; then
     echo "Failed to publish the Docker container. Exiting..."
